[package]
name = "abr_common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version="1.0.192", features=["derive", "rc"]}
serde_json = "1.0.108"
static_assertions = "1.1.0"
num-traits = "0.2.15"

ds = {path = "../ds"}
cc_common = {path = "../cc_common"}
